definitions:
  controller.ErrorResponse:
    properties:
      detail:
        type: string
      message:
        type: string
      ok:
        type: string
    type: object
  controller.TokenResponse:
    properties:
      access_token:
        type: string
      message:
        type: string
    type: object
  dto.Auth:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: amr.rostam@gmail.com
    name: A. Rostami
  description: Fiber go web framework based REST API boilerplate
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Fiber Go Auth
  version: "1.0"
paths:
  /v1/login:
    post:
      consumes:
      - application/json
      description: Create a new access token.
      parameters:
      - description: Request for token
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dto.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: create a new access token
      tags:
      - Token
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
